name: Build Visual Studio SSRS Project Release
description: Create a zip file for a Visual Studio SSRS project build
author: Lee Lott

inputs:
  project-file-name:
    description: 'The name of the Visual Studio SSRS project file (.rptporoj) to be built'
    required: true
  project-folder-path:
    description: 'The path to the folder that contains the Visual Studio SSRS project file (.rptproj) to be built'
    required: true
  prerelease:
    description: 'Mark the release as a pre-release (true/false)'
    required: true    
  prerelease-suffix:
    description: 'The name to append to the version number on releases that are marked as pre-release.  If not a pre-release, the release version will be based on the latest pre-release version using this name.'
    required: true
  configuration:
    description: 'The build configuration to use for the .NET project (e.g., Debug, Release)'
    required: true    
  package-name:
    description: 'The base name for the zip file containing the build artifacts'
    required: true
  token:
    description: 'The GitHub token used for authentication to create the release'
    required: true

outputs:
  version-tag:
    description: 'The new tag created for the release'
    value: ${{ steps.new-tag.outputs.version-tag }}
  version-number:
    description: 'The new tag with the "v" prefix removed'
    value: ${{ steps.new-tag.outputs.version-number }}
  zip-file-name:
    description: 'The name of the zip file containing the build artifacts (with the .zip extension)'
    value: ${{ steps.generate-zip-file-name.outputs.zip_file_name }}
  zip-file-path:
    description: 'The path to the zip file containing the build objects'
    value: ${{ steps.create-zip-file.outputs.package_file_path }}
  build-status:
    description: 'The build/release outcome: Release Created, No Release, or Release Failed.'
    value: ${{ steps.set-build-status.outputs.build_status }}        

runs:
  using: "composite"
  steps:
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Get Next Semantic Version Number
      id: new-tag
      uses: lee-lott-actions/get-next-semantic-version-number@v1
      with:
        prerelease: ${{ inputs.prerelease }}
        prerelease-identifier: ${{ inputs.prerelease-suffix }}
        owner: ${{ github.repository_owner }}
        repo-name: ${{ github.event.repository.name }}
        branch: ${{ github.head_ref }}
        token: ${{ inputs.token }}

    - name: Set Build Status
      id: set-build-status
      run: |
        if ("${{ steps.new-tag.outputs.result }}" -eq "success") {
          if ("${{ steps.new-tag.outputs.release-type }}" -ne "none") {
            "build_status=Release Created" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          } else {
            "build_status=No Release" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          }
        } else {
          "build_status=Release Failed" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        }
      shell: pwsh        

    - name: Generate Zip File Name
      id: generate-zip-file-name
      if: steps.set-build-status.outputs.build_status == 'Release Created'
      run: |
        $zipFileName = "${{ inputs.package-name }}.${{ steps.new-tag.outputs.version-number }}.zip"
        Write-Output "Zip File Name:  $zipFileName"
        Write-Output "zip_file_name=$zipFileName" >> $env:GITHUB_OUTPUT
      shell: pwsh

    - name: Build Project
      if: steps.set-build-status.outputs.build_status == 'Release Created'
      run: |
        Write-Output "Building Reports..."
        msbuild ${{ inputs.project-folder-path }}\${{ inputs.project-file-name }} /t:Build /p:Configuration=${{ inputs.configuration }} /p:OutputPath="bin\${{ inputs.configuration }}" /p:TargetFrameworkVersion=v4.8
        Write-Output "Build completed. Copying files to publish directory..."
        
        New-Item -Path "${{ github.workspace }}\publish" -ItemType Directory -Force
        Copy-Item -Path "${{ github.workspace }}\${{ inputs.project-folder-path }}\bin\${{ inputs.configuration }}\*" -Destination "${{ github.workspace }}\publish" -Recurse
        Write-Output "Listing publish directory:"
        Get-ChildItem -Path "${{ github.workspace }}\publish"
      shell: pwsh      
         
    - name: Create Zip Release File
      if: steps.set-build-status.outputs.build_status == 'Release Created'
      id: create-zip-file
      run: |
        Write-Output "Creating Zip File..."
        New-Item -ItemType Directory -Path ./packages -Force
        Set-Location -Path "${{ github.workspace }}\publish"
        Compress-Archive -Path ./* -DestinationPath "${{ github.workspace }}/packages/${{ steps.generate-zip-file-name.outputs.zip_file_name }}"
        $packageFilePath = "${{ github.workspace }}/packages/${{ steps.generate-zip-file-name.outputs.zip_file_name }}"
        Write-Output "Zip File Path:  $packageFilePath"
        Write-Output "package_file_path=$packageFilePath" >> $env:GITHUB_OUTPUT        
      shell: pwsh

    - name: Create Git Tag for new version
      id: create-git-tag
      if: steps.set-build-status.outputs.build_status == 'Release Created' && inputs.prerelease == 'true'
      uses: lee-lott-actions/create-git-tag@v1
      with:
        branch-name: ${{ github.base_ref }}
        tag-name: ${{ steps.new-tag.outputs.version-tag }}
        tag-message: 'Tag generated for Pull Request #${{ github.event.pull_request.number }}'
        repo-name: ${{ github.event.repository.name }}
        org-name: ${{ github.repository_owner }}
        token: ${{ inputs.token }}      

    - name: Set Current Date and Time
      id: set-date-time
      if: steps.set-build-status.outputs.build_status == 'Release Created' && inputs.prerelease == 'false'      
      run: |
        $currentDateTime = (Get-Date).ToUniversalTime().AddHours(-5).ToString("MM/dd/yyyy hh:mm:ss tt")
        "current_date_time=$currentDateTime" >> $env:GITHUB_OUTPUT
      shell: pwsh

    - name: Create GitHub Release
      id: create-release
      if: steps.set-build-status.outputs.build_status == 'Release Created' && inputs.prerelease == 'false'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.new-tag.outputs.version-tag }}
        name: ${{ steps.new-tag.outputs.version-tag }}
        draft: false
        prerelease: ${{ inputs.prerelease }}
        generate_release_notes: true
        files: ${{ inputs.prerelease != 'true' && steps.create-zip-file.outputs.package_file_path || '' }}
        body: |
          Automated Release from the ${{ github.head_ref }} branch via [Pull Request #${{ github.event.pull_request.number }}](${{ github.event.pull_request.html_url }}).
          Released on: ${{ steps.set-date-time.outputs.current_date_time }} CDT
      env:
        GITHUB_TOKEN: ${{ inputs.token }}

    - name: Set PR Message
      id: set-pr-message
      shell: pwsh
      run: |
        switch ($env:BUILD_STATUS) {
          "Release Failed" {
            "pr_message=No release version was created for this Pull Request because the tag creation step did not succeed." | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          }
          "Release Created" {
            "pr_message=This Pull Request created a new release version: $env:NEW_TAG_VERSION_TAG" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          }
          "No Release" {
            "pr_message=No release version was created for this Pull Request because conventional commits did not indicate an increase to the MAJOR, MINOR or PATCH." | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          }
          Default {
            "pr_message=Unknown build status." | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          }
        }
      env:
        BUILD_STATUS: ${{ steps.set-build-status.outputs.build_status }}
        NEW_TAG_VERSION_TAG: ${{ steps.new-tag.outputs.version-tag }}        

    - name: Comment on Pull Request
      id: comment-pr
      uses: lee-lott-actions/set-pull-request-review-status@v1
      with:
        pr-number: ${{ github.event.pull_request.number }}
        repo-name: ${{ github.event.repository.name }}
        org-name: ${{ github.repository_owner }}
        pr-status: 'COMMENT'
        pr-message: '${{ steps.set-pr-message.outputs.pr_message }}'
        token: ${{ inputs.token }}        

    - name: Add to Job Summary
      run: |
        Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value "# GitHub Release Summary"
        switch ("${{ steps.set-build-status.outputs.build_status }}") {
          "Release Created" {
            Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value "Created release **${{ steps.new-tag.outputs.version-tag }}** for Pull Request [#${{ github.event.pull_request.number }}](${{ github.event.pull_request.html_url }})."
            Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value "Release URL: [${{ steps.new-tag.outputs.version-tag }}](https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/releases/tag/${{ steps.new-tag.outputs.version-tag }})"
            Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value "Package: ${{ steps.generate-zip-file-name.outputs.zip_file_name }}"
          }
          "No Release" {
            Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value "No release created due to no qualifying commits (e.g., feat or fix required)."
          }
          "Release Failed" {
            Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value "No release created because the tag creation step did not succeed."
          }
          Default {
            Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value "Unknown build status."
          }
        }
      shell: pwsh